spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MyMoto
    username: postgres
    password: 1234abcd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true # Needed to use forbidden words as table name surrounding them by quotes
    database: postgresql

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days